config/routes.rb
Rails.application.routes.draw do
  get 'taskcomponents/create'
  get 'link_components/create'
  devise_for :users
  root to: "pages#landing"
  get '/landing', to: 'pages#landing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  resources :themes do
    resources :topics, only: [:show, :new, :create, :edit, :update]

    member do
      get 'favorite', to: 'themes#favorite', as: :favorite
      get 'unfavorite', to: 'themes#unfavorite', as: :unfavorite
    end
  end

  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :update, :edit, :destroy_item]
  end

  resources :items, only: [:show, :edit, :update, :destroy_item] do
    delete 'destroy_item', on: :member
    resources :text_components, only: [:new, :create, :update]
    resources :link_components, only: [:new, :create, :update]
    resources :task_components, only: [:new, :create, :update]
    resources :calendar_components, only: [:new, :create, :update]
    resources :locations, only: [:create]
  end

  resources :text_components, only: [:destroy]
  resources :link_components, only: [:destroy]
  resources :task_components, only: [:destroy]
  resources :calendar_components, only: [:destroy]
  resources :location_components, only: [:destroy]


end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  has_many :topics, dependent: :destroy
  has_many :items, through: :topics
  has_many :task_components, through: :items
  has_many :calendar_components, through: :items
  # has_many :collaborations
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description],
    using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def favorite
    @theme = Theme.find(params[:id])
    @theme.favorite = true
    if @theme.save
      redirect_to themes_path, notice: 'Theme favorited successfully.'
    else
      redirect_to themes_path, alert: 'Failed to favorite theme.'
    end
  end

  def unfavorite
    @theme = Theme.find(params[:id])
    @theme.favorite = false
    if @theme.save
      redirect_to request.referrer, notice: 'Theme unfavorited successfully.'
    else
      redirect_to request.referrer, alert: 'Failed to unfavorite theme.'
    end
  end

  def index
    if params[:query].nil? || params[:query] == ''
      @themes = current_user.themes
    else
      @themes = Theme.search_by_title_and_description(params[:query])
    end
    # @themes = Theme.all
    @topics = Topic.all
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    @theme.user = current_user
    if @theme.save
      redirect_to themes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @theme.user = current_user
    @themes = Theme.all
    @topics = @theme.topics
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
      redirect_to theme_path(@theme)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @theme.destroy
    redirect_to themes_path, status: :see_other
  end


  private
  def set_theme
    @theme = current_user.themes.find(params[:id])
  end

  def theme_matches_search?(theme)
    theme.title.downcase.include?(params[:query].downcase)
  end


  def theme_params
    params.require(:theme).permit(:title, :description, :photo)
  end
end

app/views/themes/_form.html.erb
<%= simple_form_for(@theme) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <% submit_label = @theme.new_record? ? "Create File" : "Update File" %>
  <%= f.button :submit, submit_label, class: "create-btn" %>
<% end %>

app/views/themes/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>Edit file</h1>
        <div class="mt-3">
          <%= render "form", theme: @theme %>
          <%= link_to "Delete File", theme_path(@theme), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "delete-file"  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/themes/index.html.erb
<div class="container topic-heading">

  <div class="theme-search-form">
    <%= form_with url: themes_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a theme..."
      %>
      <%= submit_tag "Search", class: "theme-search-submit" %>
    <% end %>
  </div>
  <div class="topics-header">
    <div class="topic-header">
      <div style="width:165px;">
      <h1></h1>
      </div>
      <div class="create-btn-icon">
        <%= link_to new_theme_path do%>
          <i class="create-btn-icon fa-solid fa-circle-plus"></i>
        <%end%>
      </div>
      <div style="width:165px;">
      <h1></h1>
      </div>
    </div>
  </div>
  <div class="themes-card-container" style="padding-top: 20px";>
    <% @themes.order(:title).each do |theme| %>
      <div class="card-favorite-btn">
        <%= link_to theme_path(theme) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= cl_image_path(theme.photo.key) if theme.photo.key.present? %>)">
            <div class="card-content">
              <h3><%= theme.title.truncate(20) %></h3>
              <p><%= theme.description.truncate(70) %></p>
            </div>
          </div>
        <% end %>
        <div class="favorite-btn">
          <% if theme.favorite? %>
            <%= link_to unfavorite_theme_path(theme), method: :patch do %>
              <i class="fas fa-heart fa-lg"></i>
            <% end %>
          <% else %>
            <%= link_to favorite_theme_path(theme), method: :patch do %>
              <i class="far fa-heart fa-lg"></i>
            <% end %>
          <% end %>
        </div>
        <div class="file-edit-btn">
          <%= link_to edit_theme_path(theme), class: "text-edit-btn" do %>
            <i class="fa-solid fa-pen"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/themes/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>New theme</h1>
        <div class="mt-3">
          <%= render "form", theme: @theme %>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="height: 10px">
  </div>

app/views/themes/show.html.erb
<div class="container topic-heading">
  <div class="topics-header">
    <div class="topic-name">
      <h3><%= @theme.title %></h3>
      <h5><%= @theme.description %></h5>
    </div>
    <div class="add-new-topic">
      <%= link_to new_theme_topic_path(@theme) do%>
        <i class="create-btn-icon fa-solid fa-circle-plus"></i>
      <%end%>
    </div>
  </div>
  <div class="themes-card-container">
    <% @topics.order(:title).each do |topic| %>
      <div class="card-favorite-btn">
        <%= link_to topic_path(topic) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(topic.photo.key) if topic.photo.key.present? %>)">
            <h3><%= topic.title.truncate(20) %></h3>
            <p><%= topic.description.truncate(70) %></p>
          </div>
        <% end %>
        <div class="file-edit-btn">
          <%= link_to edit_topic_path(topic), class: "text-edit-btn" do %>
            <i class="fa-solid fa-pen"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Back", themes_path, :class => "create-btn" %>
</div>