config/routes.rb
Rails.application.routes.draw do
  get 'taskcomponents/create'
  get 'link_components/create'
  devise_for :users
  root to: "pages#landing"
  get '/landing', to: 'pages#landing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  resources :themes do
    resources :topics, only: [:show, :new, :create, :edit, :update]

    member do
      get 'favorite', to: 'themes#favorite', as: :favorite
      get 'unfavorite', to: 'themes#unfavorite', as: :unfavorite
    end
  end

  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :update, :edit, :destroy_item]
  end

  resources :items, only: [:show, :edit, :update, :destroy_item] do
    delete 'destroy_item', on: :member
    resources :text_components, only: [:new, :create, :update]
    resources :link_components, only: [:new, :create, :update]
    resources :task_components, only: [:new, :create, :update]
    resources :calendar_components, only: [:new, :create, :update]
    resources :locations, only: [:create]
  end

  resources :text_components, only: [:destroy]
  resources :link_components, only: [:destroy]
  resources :task_components, only: [:destroy]
  resources :calendar_components, only: [:destroy]
  resources :location_components, only: [:destroy]


end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :theme
  # belongs_to :user
  has_many :items, dependent: :destroy

  has_one_attached :photo

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_theme, only: [:new, :create]
  before_action :set_topic, only: [:edit, :update, :destroy, :show]


  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.theme = @theme
    if @topic.save
      redirect_to theme_path(@theme)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @items = @topic.items
    @item = Item.new
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path(@topic)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @topic.destroy
    redirect_to theme_path(@topic.theme), status: :see_other
  end

  private
  def set_theme
    @theme = Theme.find(params[:theme_id])
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description, :photo)
  end
end

app/views/topics/_form.html.erb
<%= simple_form_for ([@theme, @topic]) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "create-btn" %>
<% end %>

app/views/topics/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>Edit File</h1>
        <div class="mt-3">
          <%= render "form", topic: @topic %>
          <%= link_to "Delete File", topic_path(@topic), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "delete-file"%>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="height: 10px">
  </div>

app/views/topics/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>New topic</h1>
        <div class="mt-3">
          <%= render "form", topic: @topic %>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="height: 10px">
  </div>

app/views/topics/show.html.erb
<div class="container topic-heading">
  <div class="topics-header">
    <div class="topic-header">
      <div style="width:165px;">
        <h1></h1>
      </div>
    </div>
  <div class="topic-name">
    <h3><%= @topic.title %></h3>
    <h5><%= @topic.description %></h5>
  </div>
  <div class="add-new-topic">
    <%= link_to new_topic_item_path(@topic, @item) do%>
      <i class="create-btn-icon fa-solid fa-circle-plus"></i>
    <%end%>
  </div>
  <div class="themes-card-container">
    <% @items.order(:title).each do |item| %>
      <div class="card-favorite-btn">
        <%= link_to item_path(item) do %>
          <% if item.photo.attached? %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path item.photo.key %>)">
          <% else %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_tag "banner.jpg" %>)">
          <% end %>
            <h3><%= item.title.truncate(25) %></h3>
            <p><%= item.description.truncate(70) %></p>
          </div>
        <% end %>
        <div class="file-edit-btn">
          <%= link_to edit_item_path(item), class: "text-edit-btn" do %>
          <i class="fa-solid fa-pen"></i>
          <% end %>
        </div>
        <div class="file-edit-btn">
          <%# link_to content_tag(:i, "", class: "fa fa-thin fa-trash-can"), item_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Back", theme_path(@topic.theme), :class => "create-btn" %>
</div>