config/routes.rb
Rails.application.routes.draw do
  get 'taskcomponents/create'
  get 'link_components/create'
  devise_for :users
  root to: "pages#landing"
  get '/landing', to: 'pages#landing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  resources :themes do
    resources :topics, only: [:show, :new, :create, :edit, :update]

    member do
      get 'favorite', to: 'themes#favorite', as: :favorite
      get 'unfavorite', to: 'themes#unfavorite', as: :unfavorite
    end
  end

  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :update, :edit, :destroy_item]
  end

  resources :items, only: [:show, :edit, :update, :destroy_item] do
    delete 'destroy_item', on: :member
    resources :text_components, only: [:new, :create, :update]
    resources :link_components, only: [:new, :create, :update]
    resources :task_components, only: [:new, :create, :update]
    resources :calendar_components, only: [:new, :create, :update]
    resources :locations, only: [:create]
  end

  resources :text_components, only: [:destroy]
  resources :link_components, only: [:destroy]
  resources :task_components, only: [:destroy]
  resources :calendar_components, only: [:destroy]
  resources :location_components, only: [:destroy]


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-sparetime" style="padding-top: 3px;padding-bottom: 0px;">
  <div class="container-fluid">
    <%= link_to "/home" do %>

      <%= image_tag "favicon.png", class: "navbar-logo" %>

    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", themes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Favorites", home_path, class: "nav-link" %>
          </li>
          <li class="dropdown">
            <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "profile.jpg", class: "avatar", alt: "dropdown menu"%>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="sidebar">
    <div class="sidebar-title"> Navigator</div>
    <% current_user.themes.order(:title).each do |theme| %>
      <div class="theme-container" data-controller="sidebar-dropdown">
        <% if theme.topics.any? %>
          <a class="theme dropdown-btn"  data-action="click->sidebar-dropdown#toggleDropdownTopics" href=""><%= theme.title%></a>
        <% else %>
          <%= link_to theme.title, theme_path(theme), class: "theme dropdown-btn" %>
        <% end %>
        <div class="dropdown-container hidden" data-sidebar-dropdown-target="topicsDropdown">
          <% theme.topics.order(:title).each do |topic| %>
            <% if topic.items.any? %>
              <a class="topic" href="" data-action="click->sidebar-dropdown#toggleDropdownItems"><%= topic.title%> </a>
            <% else %>
              <%= link_to topic.title, topic_path(topic), class: "topic" %>
            <% end %>
            <div class="hidden" data-sidebar-dropdown-target="itemsDropdown">
              <% topic.items.order(:title).each do |item| %>
                <%= link_to item.title, item_path(item), class: 'item', id: 'item-hover'%>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>