config/routes.rb
Rails.application.routes.draw do
  get 'taskcomponents/create'
  get 'link_components/create'
  devise_for :users
  root to: "pages#landing"
  get '/landing', to: 'pages#landing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  resources :themes do
    resources :topics, only: [:show, :new, :create, :edit, :update]

    member do
      get 'favorite', to: 'themes#favorite', as: :favorite
      get 'unfavorite', to: 'themes#unfavorite', as: :unfavorite
    end
  end

  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :items, only: [:new, :create, :update, :edit, :destroy_item]
  end

  resources :items, only: [:show, :edit, :update, :destroy_item] do
    delete 'destroy_item', on: :member
    resources :text_components, only: [:new, :create, :update]
    resources :link_components, only: [:new, :create, :update]
    resources :task_components, only: [:new, :create, :update]
    resources :calendar_components, only: [:new, :create, :update]
    resources :locations, only: [:create]
  end

  resources :text_components, only: [:destroy]
  resources :link_components, only: [:destroy]
  resources :task_components, only: [:destroy]
  resources :calendar_components, only: [:destroy]
  resources :location_components, only: [:destroy]


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :topic
  # has_many :components, dependent: :destroy
  has_one_attached :photo
  has_many :locations, dependent: :destroy

  has_many :calendar_components, dependent: :destroy

  has_many :task_components, dependent: :destroy
  has_many :text_components, dependent: :destroy
  def start_time
    self.calendar_component.start
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_topic, only: [:create]
  before_action :set_item, only: [:update, :edit, :destroy_item]

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    # @components = @item.components
    @text = TextComponent.new
    @texts = TextComponent.where(item: @item)

    @link = LinkComponent.new
    @links = LinkComponent.where(item: @item)
    @topic = @item.topic

    @task = TaskComponent.new
    @tasks = TaskComponent.where(item: @item)

    @calendar = CalendarComponent.new
    @calendars = CalendarComponent.where(item: @item)



    # @hope = LinkThumbnailer.generate('http://stackoverflow.com')

    # MAP ---------
    @location = Location.new
    @locations = @item.locations
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {location: location})
      }
    end
    # END MAP ------
  end

  def new
    @item = Item.new
    @topic = Topic.find(params[:topic_id])
  end

  def create
    @item = Item.new(item_params)
    @item.topic = @topic
    if @item.save!
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @text = TextComponent.find(params[:id])
    @text.destroy
    redirect_to item_path(@text.item), status: :see_other

    @link = LinkComponent.find(params[:id])
    @link.destroy
    redirect_to item_path(@link.item), status: :see_other

    @task = TaskComponent.find(params[:id])
    @task.destroy
    redirect_to item_path(@task.item), status: :see_other

    @location = LocationComponent.find(params[:id])
    @location.destroy
    redirect_to item_path(@location.item), status: :see_other

    @event = EventComponent.find(params[:id])
    @event.destroy
    redirect_to item_path(@event.item), status: :see_other
  end

  def destroy_item
    @item.destroy
    redirect_to topic_path(@item.topic), status: :see_other
  end

  private
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :photo)
  end
end

app/views/items/_form.html.erb
<%= simple_form_for([@topic, @item]) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "create-btn" %>
<% end %>

app/views/items/_info_window.html.erb
<h5><%= location.name %></h5>

app/views/items/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>Edit File</h1>
        <div class="mt-3">
          <%= render "form", topic: @item %>
          <%= link_to "Delete File", destroy_item_item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "delete-file"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="theme-form">
        <h1>New item</h1>
        <div class="mt-3">
          <%= render "form", item: @item %>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="height: 10px">
  </div>

app/views/items/show.html.erb
<div class="container">
  <div class="item-name">
    <h1><%= @item.title %></h1>
  </div>
<%# -------------------------------------- Text component ----------------------------------------------- %>
  <div class="show-text-card">
    <div class="text-title">
      <h3>Notepad</h3>
      <a type="button" class="text-btn" data-bs-toggle="modal" data-bs-target="#ModalText">
        <i class="fa-solid fa-circle-plus"></i>
      </a>
    </div>
    <div class="show-text">
      <% @texts.each do |text| %>
        <div class="text-content">
          <p><%= text.paragraph %></p>
          <a type="button" class="text-edit-btn" data-bs-toggle="modal" data-bs-target="#ModalText">
            <i class="fa-solid fa-pen"></i>
          </a>
        </div>
        <%= simple_form_for [@item, text] do |f| %>
          <div class="modal fade" id="ModalText" tabindex="-1" aria-labelledby="ModalText" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="ModalText">Add text to notepad</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div class="text-form">
                    <div class="d-flex align-items-center justify-content-start">
                      <%= f.input :paragraph, class: 'form-control',input_html: { onchange: "this.form.submit()" } %>
                      <%# f.submit %><%# end %>
                      <%= button_tag type: 'submit', class: "text-edit-btn" do %> <i class="fa-solid fa-pen"></i><% end %>
                      <%= link_to content_tag(:i, "", class: "fa fa-thin fa-trash-can"), text_component_path(text), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>


<!-- Modal -->
  <div class="modal fade" id="ModalText" tabindex="-1" aria-labelledby="ModalText" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalText">Add text to notepad</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="text-form">
            <%= simple_form_for [@item, @text] do |f| %>
              <%= f.input :paragraph, placeholder: "Write here..."%>
              <%= f.submit 'Create', class: "create-btn" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<%# ----------------------------------------- link component ------------------------------------- %>
  <div class="link-task-row">
    <div class="show-link-card">
        <div class="component-title">
          <h3>Links</h3>
          <a type="button" class="link-btn" data-bs-toggle="modal" data-bs-target="#ModalLink">
            <i class="fa-solid fa-circle-plus"></i>
          </a>
        </div>
      <div class="show-url">
        <% @links.each do |link| %>
          <% object = LinkThumbnailer.generate(link.url) %>
          <div class="link-gem-container">
            <%= image_tag object.images.first.src.to_s, alt: "Link image", width: 200 %>
            <div class="link-gem">
              <%= link_to content_tag(:i, "", class: "fa fa-thin fa-trash-can link-trash"), link_component_path(link), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
              <h3><%= link_to object.title, link.url %></h3>
              <p><%= object.description %></p>
            </div>
          </div>
        <% rescue StandardError => e %>
          <div class="link-gem-container">
            <%= image_tag 'default_thumbnail.png', alt: "Default thumbnail", width: 200 %>
            <div class="link-gem">
              <h3>Error</h3>
              <p>Failed to generate thumbnail for <%= link.url %>. Please try again later.</p>
            </div>
          </div>
        <% end %>
      <!-- Modal -->
        <div class="modal fade" id="ModalLink" tabindex="-1" aria-labelledby="ModalLink" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalLink">Insert a link:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="link-form">
                  <%= simple_form_for [@item, @link] do |f| %>
                    <%= f.input :url, placeholder: "www.example.com" %>
                    <%= f.submit 'Generate', class: "create-btn" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  <%# ------------------------------ task component ---------------------------------------------------- %>

    <div class="show-task-card">
      <div class="task-title">
        <h3>Task list</h3>
        <a type="button" class="link-btn" data-bs-toggle="modal" data-bs-target="#ModalTask">
          <i class="fa-solid fa-circle-plus"></i>
        </a>
      </div>
      <ul class="show-text">
        <% @tasks.each do |task| %>
          <%= simple_form_for [@item, task] do |f| %>
            <div class="d-flex align-items-center justify-content-start" >
              <%= f.input :completed, as: :boolean, label: false, class: 'form-control', input_html: { onchange: "this.form.submit()" } %>
              <div class="task-content">
                <h3><%=  task.title %>: </h3> <p><%= task.details %></p>
              </div>
              <a type="button" class="text-edit-btn" data-bs-toggle="modal" data-bs-target="#ModalTaskEdit<%= task.id %>">
                <i class="fa-solid fa-pen"></i>
              </a>
              <div class="modal fade" id="ModalTaskEdit<%= task.id %>"tabindex="-1" aria-labelledby="ModalTaskEdit" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="ModalTaskEdit">Edit task:</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="task-form">
                        <%= f.input :title , class: 'form-control',input_html: { onchange: "this.form.submit()" } %>
                        <%= f.input :details, class: 'form-control',input_html: { onchange: "this.form.submit()" } %>
                        <%= button_tag type: 'submit', class: "text-edit-btn" do %> <i class="fa-solid fa-pen"></i><% end %>
                        <%= link_to content_tag(:i, "", class: "fa fa-thin fa-trash-can"), task_component_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="ModalTask" tabindex="-1" aria-labelledby="ModalTask" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="ModalTask">Add a task:</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="task-form">
              <%= simple_form_for [@item, @task] do |f| %>
                <div class="form-group">
                  <%= f.input :title, class: 'form-control', placeholder: "Grocery shopping..." %>
                </div>
                <div class="form-group">
                  <%= f.input :details, class: 'form-control', placeholder: "Milk, Chicken..." %>
                </div>
                <%= f.submit 'Create task', class: 'create-btn' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<%# ------------------------------ Event component ---------------------------------------------------- %>
  <div class="calendar-map-row">
    <div class="calendar-form show-event-card">
      <div class="component-title">
        <h3>Events</h3>
        <a type="button" class="link-btn" data-bs-toggle="modal" data-bs-target="#ModalEvent">
          <i class="fa-solid fa-circle-plus"></i>
        </a>
      </div>
      <div class="event-display-container">
        <% @calendars.each do |calendar| %>
          <%= simple_form_for [@item, calendar] do |f| %>
            <div class="event-display-item">
              <div>
              <h5><strong><%= calendar.start_time %></strong></h5>
              <h4><%= calendar.name %></h4>
              </div>
              <div class="pen">
              <a type="button" class="text-edit-btn" data-bs-toggle="modal" data-bs-target="#ModalEventEdit">
                <i class="fa-solid fa-pen"></i>
              </a>
              </div>
              <div class="modal fade" id="ModalEventEdit" tabindex="-1" aria-labelledby="ModalEvent" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="ModalEventEdit">Edit the event</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="event-form">
                        <%= f.input :start_time, class: 'form-control', input_html: { onchange: "this.form.submit()" } %>
                        <%= f.input :name, class: 'form-control', input_html: { onchange: "this.form.submit()" } %>
                        <%= button_tag type: 'submit', class: "text-edit-btn" do %> <i class="fa-solid fa-pen"></i><% end %>
                        <%= link_to content_tag(:i, "", class: "fa fa-thin fa-trash-can"), calendar_component_path(calendar), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= simple_form_for [@item, @calendar] do |f| %>
        <!-- Modal -->
        <div class="modal fade" id="ModalEvent" tabindex="-1" aria-labelledby="ModalEvent" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalEvent">Create an event:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="event-form">
                  <div class="input-group">
                    <%= f.input :start_time,
                                as: :string,
                                class: 'mb-2',
                                label: "Date:",
                                input_html: { data: { controller: "datepicker" } } %>
                  </div>
                    <%= f.input :name, label: "Event description:"%>
                    <%= f.submit 'Create event', class: "create-btn" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <%# ------------------------------ Location component ---------------------------------------------------- %>


    <div class="show-map-card">
      <div class="component-title">
        <h3>Location</h3>
        <a type="button" class="link-btn" data-bs-toggle="modal" data-bs-target="#ModalLocation">
          <i class="fa-solid fa-circle-plus"></i>
        </a>
      </div>
      <div class="link-form">
        <!-- Modal -->
        <div class="modal fade" id="ModalLocation" tabindex="-1" aria-labelledby="ModalLocation" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalLocation">Add a location:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="location-form">
                  <%= simple_form_for [@item, @location] do |f| %>
                    <%= f.input :name, placeholder: "e.g., Restaurants" %>
                    <%= f.input :address, placeholder: "123 Abbey Road" %>
                    <%= f.submit 'Add location', class: "create-btn" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="map-container">
        <div class="map-box" style="width: 100%; height: 400px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Back", topic_path(@topic), :class => "create-btn" %>